project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    right: 
      - icon: linkedin 
        href: https://www.linkedin.com/in/benjaminrubin64
      - icon: github
        href: https://github.com/kebertxela-BR
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "TidyTuesday"
        contents:
          - text: NYT Best Sellers
            href: ./TidyTuesday/NYT_BestSellers.qmd
          - text: Board Games!
            href: ./TidyTuesday/Board_games1.qmd
      - section: "Published Work"
        contents:
          - text: Quantitative Functionalization of the Tyrosine Residues in Silk Fibroin through an Amino-Tyrosine Intermediate.
            href: https://onlinelibrary.wiley.com/doi/abs/10.1002/macp.202200119
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"

editor: visual