project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: linkedin 
        href: https://www.linkedin.com/in/benjaminrubin64
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "TidyTuesday"
        contents:
          - NYT_BestSellers.qmd
          - Board_games1.qmd
      - section: "Projects"
        contents: 
          - Freedom_Index.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"

editor: visual