---
title: "Best Board Games"
date: 2023-02-07
output: html_output
execute: 
  echo: true
  warning: false
---

# Best Board Games

This data set comes from [BoardGameGeekReviews](https://www.kaggle.com/datasets/jvanelteren/boardgamegeek-reviews?select=2022-01-08.csv) on Kaggle

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(DT)
library(gt)
library(ggiraph)

```

```{r Load, include=FALSE}

tt <- tt_load("2022-01-25")

```

# Wrangle

```{r Wrangle}


ratings=tt$ratings
details=tt$details

best_ranked_games <- function(game_name = NULL, game_rank = rank) {

    if (!is.null(game_name)) {

        ratings <- ratings %>%

            filter(name == game_name)

    }

    ratings %>%

        top_n (-50, {

            {

                game_rank

            }

        }) %>%

        arrange({

            {

                game_rank

            }

        }) %>%

        select(name, image = thumbnail,rank, average,users_rated,year) %>%

        gt() %>%

        text_transform(locations = cells_body(vars(image)), fn = function(x) {

            web_image(url = x, height = 50)

        })

}

```

# Tables

```{r Visualize}

best_ranked_games()
  
```

# 

```{r}
game_details=ratings %>% 
  arrange(rank) %>%
  select(id,rank,average) %>% 
  right_join(details,by=c("id"="id")) %>% 
  mutate("logmin"=log10(minplaytime),minplayers=as.factor(minplayers))

top_50_details=game_details %>% 
  top_n(-50,rank) %>% 
  select(1:13,-description,-rank,-num, logmin)

```

```{r}
callback <- c(
  "$('#DataTables_Table_0_length select').css('color', '#fff');",
  "$('#DataTables_Table_0_filter input').css('color', '#fff');"
)


datatable(top_50_details, callback=JS(callback), options = list(
  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#222', 'color': '#fff'});",
    "$(this.api().table().container()).css({'background-color': '#222', 'color': '#fff'})",
    "}"))) %>% 
  formatStyle(1:13,color="white")


```

```{r}
g=top_50_details %>%
  ggplot(aes(x= logmin, y=average, color = minplayers))+
  scale_x_continuous(limits=c(1,3))+
  scale_y_continuous(limits=c(7.5,9))+
  labs(title= "Ranking vs Minimum Time Required (Top 50)")

my_gg = g + 
  geom_point_interactive(aes(tooltip = primary, data_id = id), 
   hover_nearest = TRUE)
css_default_hover <- girafe_css_bicolor(primary = "yellow", secondary = "red")

set_girafe_defaults(
  opts_hover = opts_hover(css = css_default_hover),
  opts_zoom = opts_zoom(min = 1, max = 4),
  opts_tooltip = opts_tooltip(css = "padding:3px;background-color:#333333;color:white;"),
  opts_sizing = opts_sizing(rescale = TRUE),
  opts_toolbar = opts_toolbar(saveaspng = FALSE, position = "bottom", delay_mouseout = 5000))

girafe(ggobj = my_gg)
```
