---
title: "Presentation of Ben"
author: "Ben Rubin"
date: 2023-02-18
format:
  revealjs:
    multiplex: true
    preview-links: true
    theme: simple
    scrollable: true
    footer: "Data Science Skills"
    html-math-method: katex
    incremental: true
    slide-number: c/t
    transition: concave
    code-fold: true
    code-tools: true
---

```{r, setup, include=FALSE}

library(tidyverse)
library(plotly)
library(shiny)
library(tidytuesdayR)
library(DT)
library(gt)
library(ggiraph)
library(ggimage)

tt <- tt_load("2022-01-25")

ratings=tt$ratings
details=tt$details

best_ranked_games <- function(game_name = NULL, game_rank = rank) {

    if (!is.null(game_name)) {

        ratings <- ratings %>%

            filter(name == game_name)

    }

    ratings %>%

        top_n (-50, {

            {

                game_rank

            }

        }) %>%

        arrange({

            {

                game_rank

            }

        }) %>%

        select(name, image = thumbnail,rank, average,users_rated,year) %>%

        gt() %>%

        text_transform(locations = cells_body(vars(image)), fn = function(x) {

            web_image(url = x, height = 50)

        })

}

game_details=ratings %>% 
  arrange(rank) %>%
  select(id,rank,average) %>% 
  right_join(details,by=c("id"="id")) %>% 
  mutate("logmin"=log10(minplaytime),minplayers=as.factor(minplayers))

top_50_details=game_details %>% 
  top_n(-50,rank) %>% 
  select(1:13,-description,-rank,-num, logmin)

callback <- c(
  "$('#DataTables_Table_0_length select').css('color', '#fff');",
  "$('#DataTables_Table_0_filter input').css('color', '#fff');"
)


datatable(top_50_details, callback=JS(callback), options = list(
  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#222', 'color': '#fff'});",
    "$(this.api().table().container()).css({'background-color': '#222', 'color': '#fff'})",
    "}"))) %>% 
  formatStyle(1:13,color="white")

knitr::opts_chunk$set(warning = FALSE,message = FALSE, echo=TRUE, comment = NA, prompt = FALSE)
```

## Works of Ben

# 

-   This presentation will show a few examples of Ben Rubin's skill in data science

# 

Here is a cool shiny app I made

```{=html}

<iframe height="500" width="100%" frameborder="no" src="https://oettj8-benjamin-rubin.shinyapps.io/freedom_index/"> </iframe>
```
This data comes from the V-Dem Dataset that contains the worlds most comprehensive and detailed democracy ratings. The ratings are based on expert knowledge ranging from low (0.00) to high (1.00).

# 

Check out these tables on board games!

::: columns
::: {.column width="50%"}
```{r}

best_ranked_games()
```
:::

::: {.column width="50%"}
```{r}

datatable(top_50_details, callback=JS(callback), options = list(
  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#222', 'color': '#fff'});",
    "$(this.api().table().container()).css({'background-color': '#222', 'color': '#fff'})",
    "}"))) %>% 
  formatStyle(1:13,color="white")
```
:::
:::
